services:
  sportfinder-app:
    build: .
    container_name: sportfinder-app
    restart: always
    expose:
      - "8080"
    env_file:
      - ./src/main/resources/application-production.properties
    networks:
      - web

networks:
  web:
    external: true
