services:
  db:
    image: postgres:15
    container_name: postgres-prod
    restart: unless-stopped
    env_file:
      - ./src/main/resources/application-production.properties
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  sportfinder-app:
    build: .
    container_name: sportfinder-app
    depends_on:
      - db
    restart: always
    expose:
      - "8080"
    env_file:
      - ./src/main/resources/application-production.properties
    networks:
      - web

volumes:
  postgres_data:

networks:
  web:
    external: true
