# Spring Boot écoute toutes les interfaces
server.address=0.0.0.0
server.port=8080

# Connexion PostgreSQL via le nom du service Docker
spring.datasource.url=jdbc:postgresql://db:5432/sportdb
spring.datasource.username=sportuser
spring.datasource.password=sportpass
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
