name: Deploy Sport-Finder

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add server to known_hosts
        run: |
          ssh-keyscan -p ${{ secrets.SERVER_PORT_SSH }} -H ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts

      - name: Create application-production.properties on server
        run: |
          ssh -i ~/.ssh/id_acces_gh -p 54987 debian@51.68.234.182 "
            cat > /home/debian/OSM-Sport-Request/src/main/resources/application-production.properties <<EOL
            # Spring Boot écoute toutes les interfaces
            server.address=0.0.0.0
            server.port=8080

            # Connexion PostgreSQL via le nom du service Docker
            spring.datasource.url=jdbc:postgresql://postgres-prod:5432/${{ secrets.POSTGRES_DB }}
            spring.datasource.username=${{ secrets.POSTGRES_USER }}
            spring.datasource.password=${{ secrets.POSTGRES_PASSWORD }}
            spring.datasource.driver-class-name=org.postgresql.Driver

            # JPA / Hibernate
            spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
            spring.jpa.hibernate.ddl-auto=update
            spring.jpa.show-sql=true

            # Profil actif
            spring.profiles.active=prod
            EOL
          "


      - name: Deploy on server
        run: |
          ssh -p ${{ secrets.SERVER_PORT_SSH }} debian@${{ secrets.SERVER_HOST }} "
            cd /home/debian/OSM-Sport-Request &&
            git pull &&
            docker compose -f docker-compose.production.yml down &&
            docker compose -f docker-compose.production.yml build --no-cache &&
            docker compose -f docker-compose.production.yml up -d
          "